# Generated by Django 5.0.4 on 2024-04-11 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('medicalName', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='body_parts/images/')),
                ('renderName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DoableProcedure',
            fields=[
                ('surgeryTechnicalName', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=255)),
                ('bodyPart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='MedVision.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('shortDescription', models.TextField(blank=True, default='', max_length=255)),
                ('imageName', models.CharField(blank=True, default='', max_length=255)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='MedVision.doableprocedure')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
