# Generated by Django 5.0.4 on 2024-04-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
