# Generated by Django 5.0.4 on 2024-04-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='shortDescription',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(),
        ),
    ]
