# Generated by Django 5.0.4 on 2024-04-11 03:04

import MedVision.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVision', '0002_alter_bodypart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodypart',
            name='image',
            field=models.ImageField(upload_to=MedVision.models.UploadToPathAndRename('media/images/')),
        ),
    ]
