# Generated by Django 5.0.4 on 2024-04-11 19:54

import MedVision.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedVision', '0003_alter_bodypart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypart',
            name='renderName',
        ),
        migrations.AddField(
            model_name='bodypart',
            name='render',
            field=models.FileField(blank=True, null=True, upload_to=MedVision.models.upload_to),
        ),
        migrations.AlterField(
            model_name='bodypart',
            name='image',
            field=models.ImageField(upload_to=MedVision.models.upload_to),
        ),
    ]
